services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messagesdb
    ports:
      - "5432:5432"

  go-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: postgres://postgres:password@postgres-db:5432/messagesdb
